import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { routing } from "@app/i18n/routing";

import { Providers } from "@process/providers";

import { LocalePropsT } from "@shared/types/system/types";

type Props = {
  children: React.ReactNode;
  params: {locale: LocalePropsT};
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({children, params}: Readonly<Props>) {
  const { locale } = await params;
  const messages = await getMessages();

  if (!routing.locales.includes(locale)) notFound();

  return (
    <>
      <NextIntlClientProvider messages={messages}>
        <Providers>
          {children}
        </Providers>
      </NextIntlClientProvider>
    </>
  );
}