import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@app/i18n/routing";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import Providers from "@app/process/providers/Providers";

import { LocaleEnumT } from "@shared/types/enum.types";


type Props = {
  children: React.ReactNode;
  params: {locale: LocaleEnumT};
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children, params}: Readonly<Props>) {
  
  const { locale } = await params;
  const messages = await getMessages();

  if (!routing.locales.includes(locale)) notFound();

  return (
    <html lang={locale} className="h-full">
      <body className={"bg-black h-inherit text-white"}>
        <NextIntlClientProvider messages={messages}>
          <Providers>
            {children}
          </Providers>
        </NextIntlClientProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
